### ISSUE TITLE
0.7.0 crashes the sim

### ISSUE THREAD

**Issue by 2hwk** [dga711/msfs-webui-devkit#11] opened 2020-09-13 04:08 UTC
After expanding the console and either sitting in the menus for a while or going in flight, the game will crash.

This did not occur in 0.6.0.

**Comment by dga711** [comment] 2020-09-14 09:20
Hi, thanks for reporting.
I guess it is the livereloading of CSS again. I thought I did everything I can do to avoid crashes caused by it.
Guess I have to roll that one back then.

**Comment by dga711** [comment] 2020-09-14 20:54
closed via 68c01c5bc1cbdfd124327538327c1eb03c846624

**Closed by dga711** 2020-09-14 20:54 UTC
